/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.mao.buildjavaapkapplication;

public final class R {
  public static final class color {
    public static final int black=0x7f010000;
    public static final int purple_200=0x7f010001;
    public static final int purple_500=0x7f010002;
    public static final int purple_700=0x7f010003;
    public static final int teal_200=0x7f010004;
    public static final int teal_700=0x7f010005;
    public static final int white=0x7f010006;
  }
  public static final class drawable {
    public static final int ic_launcher_background=0x7f020001;
    public static final int ic_launcher_foreground=0x7f020002;
  }
  public static final class layout {
    public static final int activity_main=0x7f030000;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f040000;
    public static final int ic_launcher_round=0x7f040001;
  }
  public static final class string {
    public static final int app_name=0x7f050000;
  }
  public static final class style {
    /**
     * <style name="Theme.BuildJavaApkApplication" parent="Theme.MaterialComponents.DayNight.DarkActionBar">
     * &lt;!&ndash; Primary brand color. &ndash;&gt;
     * <item name="colorPrimary">@color/purple_500</item>
     * <item name="colorPrimaryVariant">@color/purple_700</item>
     * <item name="colorOnPrimary">@color/white</item>
     * &lt;!&ndash; Secondary brand color. &ndash;&gt;
     * <item name="colorSecondary">@color/teal_200</item>
     * <item name="colorSecondaryVariant">@color/teal_700</item>
     * <item name="colorOnSecondary">@color/black</item>
     * &lt;!&ndash; Status bar color. &ndash;&gt;
     * <item name="android:statusBarColor" tools:targetApi="l">?attr/colorPrimaryVariant</item>
     * &lt;!&ndash; Customize your theme here. &ndash;&gt;
     * </style>
     */
    public static final int AppTheme=0x7f060000;
  }
}